# Generated by Django 4.2 on 2025-12-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('final_transcript', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
